# Generated by Django 5.2.3 on 2025-06-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol_api', '0007_alter_student_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='age',
            new_name='age_group',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='name_group',
        ),
    ]
