# Generated by Django 5.2.3 on 2025-06-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol_api', '0008_rename_age_group_age_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postphoto',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='postvideo',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='postphoto',
            name='order',
        ),
        migrations.RemoveField(
            model_name='postvideo',
            name='order',
        ),
    ]
