# Generated by Django 5.2.3 on 2025-06-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol_api', '0010_remove_post_caption_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
