# Generated by Django 5.2.3 on 2025-06-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol_api', '0012_alter_postphoto_photo_alter_postvideo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name_group',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='new group', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usercontrol_api.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель')], default='student', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
