# Generated by Django 5.2.3 on 2025-06-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol_api', '0013_remove_group_age_group_remove_group_name_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postphoto',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostVideo',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostPhoto',
        ),
    ]
