# Generated by Django 5.2.3 on 2025-06-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol_api', '0014_remove_post_author_remove_postphoto_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель')], default='teacher', max_length=7),
        ),
    ]
