# Generated by Django 5.2.3 on 2025-06-14 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('conference', 'конференция'), ('contest', 'конкурс'), ('excursion', 'экскурсия'), ('seminar', 'семинар')], default='conference', max_length=10),
        ),
    ]
