# Generated by Django 5.2.3 on 2025-06-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('конференция', 'Conference'), ('конкурс', 'Contest'), ('экскурсия', 'Excursion'), ('семинар', 'Seminar')], default='конференция', max_length=11),
        ),
    ]
