# Generated by Django 5.2.3 on 2025-06-17 09:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0002_post_event_date_post_type'),
        ('usercontrol_api', '0015_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPhoto',
            new_name='EventPhoto',
        ),
        migrations.RenameModel(
            old_name='PostVideo',
            new_name='EventVideo',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('conference', 'конференция'), ('contest', 'конкурс'), ('excursion', 'экскурсия'), ('seminar', 'семинар')], default='conference', max_length=10)),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usercontrol_api.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='event_api.event'),
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='event_api.event'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
