# Generated by Django 5.2.3 on 2025-06-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0004_event_attendees_event_max_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(max_length=1000),
        ),
    ]
