# Generated by Django 5.2.3 on 2025-06-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0006_alter_event_max_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
