# Generated by Django 5.2.3 on 2025-06-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0007_alter_event_max_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
